services:
  db:
    image: postgres:16-alpine
    container_name: eeum-db
    restart: always
    environment:
      POSTGRES_DB: eeum
      POSTGRES_USER: eeum
      POSTGRES_PASSWORD: eeum
    networks:
      - eeum-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eeum -d eeum -h localhost -p 5432"]
      interval: 5s
      timeout: 3s
      retries: 30
    volumes:
      - eeum-postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: eeum-redis
    restart: always
    command: ["redis-server","--appendonly","yes"]
    networks:
      - eeum-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - eeum-redis-data:/data

  eeum:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: eeum:latest
    container_name: eeum
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - eeum-net
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: "8081"
      DB_URL: jdbc:postgresql://db:5432/eeum
      DB_USERNAME: eeum
      DB_PASSWORD: eeum
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      MQTT_BROKER: tcp://mosquitto:1883
      MQTT_USERNAME: eeum
      MQTT_PASSWORD: ssafy2086eeum
    expose:
      - "8081"

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    restart: always
    depends_on:
      eeum:
        condition: service_started
    networks:
      - eeum-net
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/nginx/conf.d:/etc/nginx/conf.d:ro
      - /srv/eeum/assets/floorplans:/usr/share/nginx/html/floorplans:ro



  adminer:
    image: adminer
    container_name: eeum-adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: eeum-db   # postgres 서비스 이름
    ports:
      - "8082:8080"                     # 브라우저 접근: http://<서버IP>:8082
    depends_on:
      - db
    networks:
      - eeum-net

networks:
  eeum-net:
    name: eeum-net   # 네트워크 이름 고정
    
volumes:
  eeum-postgres-data:
  eeum-redis-data:
